# Generated by Django 3.1.7 on 2021-04-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(default='', max_length=8)),
                ('type', models.CharField(default='U', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profile', models.CharField(default='avatar.jpg', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('log', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('log', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('log', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('log', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
                ('student', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(default='avatar.pdf', max_length=30)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('teacher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
